name: Build and Publish Docker Image
on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u levgiorg -p ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build Docker image
        run: |
          docker build \
            --platform=linux/amd64 \
            -f Dockerfile \
            -t levgiorg/your_ml_model:latest \
            .

      - name: Push Docker image
        run: docker push levgiorg/your_ml_model:latest